build.gradle, src/main/java/Core/Commands/RecommendationCommand.java, src/main/java/Core/Discord/EventCore.java, src/main/java/Core/HTTP/HttpApi.java, src/main/java/Core/InderesAPI/DataStructures/RecommendationEntry.java, src/main/java/Core/InderesAPI/InderesConnector.java, src/main/java/Core/InderesAPI/InderesConnectorImpl.java, src/main/java/Core/Main.java, src/main/java/Core/YahooAPI/DataStructures/FundamentalTimeSeries/FundaEntry.java, src/main/java/Core/YahooAPI/DataStructures/FundamentalTimeSeries/FundaMeta.java, src/main/java/Core/YahooAPI/DataStructures/FundamentalTimeSeries/FundaValue.java, src/main/java/Core/YahooAPI/DataStructures/Fundamentals/FundaEntry.java, src/main/java/Core/YahooAPI/YahooConnectorImpl.java
Integrated to Inderes API which provides price target and recommendations for some OMXH and first north stocks, this data can be accessed by !recommendation command
=> Integrate to Inderes API for recommendation data

src/main/java/Core/Commands/RecommendationCommand.java
Added help text, and changed recommendation commands search function to use ISIN code instead of stock name to get right results
=> Add help text to recommendation command and query price by ISIN code

src/main/java/Core/Commands/CalendarCommand.java, src/main/java/Core/Commands/Price.java, src/main/java/Core/Commands/RecommendationCommand.java, src/main/java/Core/Commands/StatisticsCommand.java, src/main/java/Core/Main.java
Created shortcut names for some commands to allow faster queries
=> Add additional one character long names for commands

src/main/java/Core/Commands/StatisticsCommand.java, src/main/java/Core/Main.java, src/main/java/Core/YahooAPI/DataStructures/DefaultKeyStatistics.java
Add PEG, EV/Revenue, EPS Growth forecast, trailing EPS, and forward EPS to statistics command
=> Add new ratios to statistics command

src/main/java/Core/Configuration/Config.java, src/main/java/Core/Discord/EventCore.java, src/main/java/Core/Permissions/PermissionManager.java
Adding configuration options to restrict channels where the bot can be used
=> Add channel restriction configurations

src/main/java/Core/Discord/MessageReacter.java
Removing redundant check of possible reactions when receiving messages from another source than text channel
=> Remove checking for reactions to private messages

Jenkinsfile, src/test/java/Core/Permissions/PermissionManagerTest.java
Remove redundancy from build pipeline
=> Remove redundancy from build pipeline

src/main/java/Core/Commands/FscoreCommand.java, src/main/java/Core/Commands/HelpCommand.java
FScore was looking back 3 quarters when comparing annual change, when it was supposed to be looking back 4 quarters
=> Fix fscore quarter offsets

build.gradle
Updating all dependency versions to latest available
=> Update dependencies to latest

gradle/wrapper/gradle-wrapper.properties, src/main/java/Core/Commands/Command.java, src/main/java/Core/Commands/FscoreCommand.java, src/test/java/Core/Commands/CommandTest.java
Adjusting permission checker behavior when user lacks any roles on the server.
Added unit tests with full branch coverage for the permission checker method
=> Adjust command permission checker and add unit tests

src/main/java/Core/Commands/BioCommand.java, src/main/java/Core/Commands/Command.java, src/main/java/Core/YahooAPI/DataStructures/AssetProfile.java, src/main/java/Core/YahooAPI/DataStructures/DataResponse.java, src/main/java/Core/YahooAPI/YahooConnectorImpl.java
Added bio command which allows to view business description of a requested company
=> Add bio command

src/main/java/Core/Commands/AboutCommand.java, src/main/java/Core/Commands/BindCommand.java, src/main/java/Core/Commands/Lunch.java, src/main/java/Core/Commands/RatiosCommand.java, src/main/java/Core/Discord/EventCore.java, src/main/java/Core/YahooAPI/YahooConnectorImpl.java
Added default responses when commands return blank response or throw exception. This in done to prevent situation when bot does not responds anything
=> Better exception handling

build.gradle, runtime/Dockerfile, runtime/build.sh, runtime/cronjob.sh, runtime/start.sh, src/main/java/Core/Commands/AltmanZScoreCommand.java, src/main/java/Core/Lunch/LunchQuery.java, src/main/java/Core/YahooAPI/YahooConnectorImpl.java
* Fixed minor bugs in lunch command
* Added altman z-score command
* Updated dependencies
* Created build files for running the application in docker container
=> New command, dependency updates, docker files

build.gradle, src/main/java/Core/Commands/Command.java, src/main/java/Core/Commands/CommandHandler.java, src/main/java/Core/Commands/RecommendationCommand.java, src/main/java/Core/Configuration/Config.java, src/main/java/Core/Configuration/ConfigLoader.java, src/main/java/Core/Configuration/OmxNordicNewsConfig.java, src/main/java/Core/Configuration/ServerConfig.java, src/main/java/Core/Discord/EventCore.java, src/main/java/Core/HTTP/HttpApi.java, src/main/java/Core/InderesAPI/DataStructures/RecommendationEntry.java, src/main/java/Core/InderesAPI/InderesConnector.java, src/main/java/Core/InderesAPI/InderesConnectorImpl.java, src/main/java/Core/Permissions/PermissionManager.java, src/main/java/Core/Schedulers/AnalystRecommendations/InderesRecommendations.java, src/main/java/Core/Schedulers/OmxNordic/NasdaqOmxNordicNews.java, src/main/java/Core/Utilities/StringUtils.java, src/main/java/Core/Utilities/VersionParser.java, src/test/java/Core/Commands/CommandTest.java, src/test/java/Core/Permissions/PermissionManagerTest.java
Notifications when inderes updates recommendations can now be posted to a specific channel.
Changed identification of channels,users,roles,servers to user unique id value in configs instead of names which more robust and still works even if people or server names change, as the ID value is always the same
=> Implement notifications for inderes recommendation changes, use ID values in configs

src/main/java/Core/Configuration/Config.java, src/main/java/Core/Discord/FilterHandler.java, src/main/java/Core/Discord/MessageReacter.java, src/main/java/Core/Schedulers/AnalystRecommendations/InderesRecommendations.java, src/main/java/Core/Schedulers/OmxNordic/NasdaqOmxNordicNews.java, src/main/java/Core/Schedulers/Shareville/SharevilleTracker.java
Change more commands to use id values instead of names
=>  Change more commands to use id values instead of names 

src/main/java/Core/HTTP/HttpApi.java, src/main/java/Core/Schedulers/OmxNordic/NasdaqOmxNordicNews.java
Update nasdaq news urls and increase delay between updates
=> Update nasdaq news urls and increase delay between updates

src/main/java/com/etsubu/stonksbot/command/RecommendationCommand.java, src/main/java/com/etsubu/stonksbot/configuration/FilterConfig.java, src/main/java/com/etsubu/stonksbot/discord/FilterHandler.java, src/main/java/com/etsubu/stonksbot/scheduler/recommendations/InderesRecommendations.java, src/main/java/com/etsubu/stonksbot/scheduler/shareville/SharevilleTracker.java, src/main/java/com/etsubu/stonksbot/yahoo/YahooConnectorImpl.java
Fixed some formatting issues when posting multiple shareville or inderes recommendation changes in same message.
Added risk measurement value to inderes recommendations when querying by command
=> Fix formatting issues in shareville and inderes recommendation changes

build.gradle, src/main/java/com/etsubu/stonksbot/discord/EventCore.java
Commands reply to original message instead of sending general response to channel
=> Commands reply to original message instead of sending general response to channel

src/main/java/com/etsubu/stonksbot/command/AboutCommand.java, src/main/java/com/etsubu/stonksbot/command/AltmanZScoreCommand.java, src/main/java/com/etsubu/stonksbot/command/BindCommand.java, src/main/java/com/etsubu/stonksbot/command/BioCommand.java, src/main/java/com/etsubu/stonksbot/command/CalendarCommand.java, src/main/java/com/etsubu/stonksbot/command/Command.java, src/main/java/com/etsubu/stonksbot/command/CommandHandler.java, src/main/java/com/etsubu/stonksbot/command/CommandResult.java, src/main/java/com/etsubu/stonksbot/command/FscoreCommand.java, src/main/java/com/etsubu/stonksbot/command/HelpCommand.java, src/main/java/com/etsubu/stonksbot/command/ListCommand.java, src/main/java/com/etsubu/stonksbot/command/Lunch.java, src/main/java/com/etsubu/stonksbot/command/Price.java, src/main/java/com/etsubu/stonksbot/command/RatiosCommand.java, src/main/java/com/etsubu/stonksbot/command/RecommendationCommand.java, src/main/java/com/etsubu/stonksbot/command/StatisticsCommand.java, src/main/java/com/etsubu/stonksbot/command/VoteLinkCommand.java, src/main/java/com/etsubu/stonksbot/command/utilities/CommandContext.java, src/main/java/com/etsubu/stonksbot/command/utilities/CommandUtilities.java, src/main/java/com/etsubu/stonksbot/configuration/ServerConfig.java, src/main/java/com/etsubu/stonksbot/discord/EventCore.java, src/test/java/com/etsubu/stonksbot/command/CommandTest.java
Create command context structure and add votelink generator
=> Create command context structure and add votelink generator

src/main/java/com/etsubu/stonksbot/scheduler/recommendations/InderesRecommendations.java
Add change percentage to inderes recommendation target changes
=> Add change percentage to inderes recommendation target changes

src/main/java/com/etsubu/stonksbot/yahoo/YahooConnector.java, src/test/java/com/etsubu/stonksbot/command/AboutCommandTest.java, src/test/java/com/etsubu/stonksbot/integration/YahooFinanceIntegrationTest.java
=> Add integration and unit tests

build.gradle, src/main/java/com/etsubu/stonksbot/Main.java, src/main/java/com/etsubu/stonksbot/discord/EventCore.java, src/main/java/com/etsubu/stonksbot/scheduler/SchedulerService.java, src/test/java/com/etsubu/stonksbot/discord/EventCoreTest.java
=> Add unit tests for event core

README.md, src/main/java/com/etsubu/stonksbot/command/Command.java, src/main/java/com/etsubu/stonksbot/command/CommandHandler.java, src/test/java/com/etsubu/stonksbot/command/CommandHandlerTest.java, src/test/java/com/etsubu/stonksbot/configuration/ConfigLoaderTest.java, src/test/resources/config.yaml
=> Add unit tests for command handler and extend config loader tests

.gitignore, Jenkinsfile, build.gradle, src/integration_test/java/com/etsubu/stonksbot/SystemTest.java, src/integration_test/java/com/etsubu/stonksbot/inderes/InderesConnectorIntegrationTest.java, src/integration_test/java/com/etsubu/stonksbot/yahoo/YahooFinanceIntegrationTest.java, src/integration_test/resources/config.yaml, src/main/java/com/etsubu/stonksbot/configuration/Config.java, src/main/java/com/etsubu/stonksbot/configuration/ConfigLoader.java, src/main/java/com/etsubu/stonksbot/discord/EventCore.java, src/test/java/com/etsubu/stonksbot/configuration/ConfigLoaderTest.java, src/test/java/com/etsubu/stonksbot/discord/EventCoreTest.java, src/test/resources/config.yaml
Created system tests and integrated those as part of pipeline in a separate stage. These tests utilize test discord server for verifying that basic commands work properly
=> Create system tests

build.gradle, gradle/wrapper/gradle-wrapper.properties, src/main/java/com/etsubu/stonksbot/command/BindCommand.java, src/main/java/com/etsubu/stonksbot/command/Command.java, src/main/java/com/etsubu/stonksbot/scheduler/recommendations/InderesRecommendations.java
* Added current stock price with upside/downside percentage to inderes recommendation changes
Previously the initial recommendation of a new company was not being notified as a new recommendation was not considered to be a recommendation change. Now initial recommendations are notified on the channel as well.
* Updated dependencies to latest
=> Add current price to inderes recommendation changes and add notification for initial recommendations of new stocks

build.gradle, src/main/java/com/etsubu/stonksbot/discord/MessageReacter.java, src/main/java/com/etsubu/stonksbot/utility/HttpApi.java
Upgrade dependencies to latest
=> Upgrade dependencies to latest

Jenkinsfile, src/main/java/com/etsubu/stonksbot/discord/FilterHandler.java
Ignore message filters for trusted and admin groups
=> Ignore message filters for trusted and admin groups

src/main/java/com/etsubu/stonksbot/discord/EventCore.java, src/main/java/com/etsubu/stonksbot/permission/PermissionManager.java, src/test/java/com/etsubu/stonksbot/permission/PermissionManagerTest.java
No error replies outside of whitelisted channel for non admin users
=> No error replies outside of whitelisted channel for non admin users

src/main/java/com/etsubu/stonksbot/administrative/GuildRoleManager.java, src/main/java/com/etsubu/stonksbot/configuration/ServerConfig.java, src/main/java/com/etsubu/stonksbot/discord/EventCore.java, src/test/java/com/etsubu/stonksbot/discord/EventCoreTest.java
Implement guild role order manager. This allows configuring order requirements for the roles in the guild ensuring that the hierarchical order is maintained when role orders change.
=> Implement guild role order manager

src/main/java/com/etsubu/stonksbot/configuration/SpringConfig.java
=> Create task scheduler

src/main/java/com/etsubu/stonksbot/yahoo/TickerStorage.java
Adjust ticker storage formating
=> Adjust ticker storage formating

src/main/java/com/etsubu/stonksbot/scheduler/shareville/SharevilleTracker.java
Send shareville requests in queue instead of parallel to avoid http2  goaway issues
=> Send shareville requests in queue instead of parallel to avoid http2  goaway issues

src/main/java/com/etsubu/stonksbot/scheduler/recommendations/InderesRecommendations.java
Improve recommendation change detection when only the date value changes
=> Improve recommendation change detection when only the date value changes

src/main/java/com/etsubu/stonksbot/scheduler/recommendations/InderesRecommendations.java
Notify when an existing company is no longer followed by inderes
=> Notify when an existing company is no longer followed by inderes

Jenkinsfile, src/main/java/com/etsubu/stonksbot/scheduler/omxnordic/Model/Transaction.java, src/main/java/com/etsubu/stonksbot/scheduler/omxnordic/Model/TransactionItem.java
Improve transaction disclosure parsing
=> Improve transaction disclosure parsing

src/main/java/com/etsubu/stonksbot/command/AltmanZScoreCommand.java, src/main/java/com/etsubu/stonksbot/command/FscoreCommand.java
=> Allow all commands by default

src/main/java/com/etsubu/stonksbot/command/BioCommand.java, src/main/java/com/etsubu/stonksbot/command/CalendarCommand.java
Not a big issue, just a minor eyesore
=> Fix mobile formatting for some commands

README.md, build.gradle, src/main/java/com/etsubu/stonksbot/scheduler/shareville/Model/Transaction.java, src/test/java/com/etsubu/stonksbot/command/CommandTest.java
Update dependencies, readme, and remove spotbugs
=> Update dependencies, readme, and remove spotbugs

build.gradle, gradle/wrapper/gradle-wrapper.properties, src/integration_test/java/com/etsubu/stonksbot/SystemTest.java, src/main/java/com/etsubu/stonksbot/discord/MessageReacter.java, src/test/java/com/etsubu/stonksbot/discord/EventCoreTest.java
=> Upgrade dependencies

src/main/java/com/etsubu/stonksbot/inderes/InderesConnectorImpl.java, src/main/java/com/etsubu/stonksbot/inderes/model/RecommendationEntry.java, src/main/java/com/etsubu/stonksbot/scheduler/recommendations/InderesRecommendations.java, src/main/java/com/etsubu/stonksbot/scheduler/recommendations/model/ChangedRecommendation.java, src/main/java/com/etsubu/stonksbot/scheduler/recommendations/model/NewRecommendation.java, src/main/java/com/etsubu/stonksbot/scheduler/recommendations/model/RecommendationChange.java, src/main/java/com/etsubu/stonksbot/scheduler/recommendations/model/RemovedRecommendation.java
Refactors the recommendation change tracking implementation to keep all recommendations immutable and utilize extra abstraction. Changes aim to make the implementation more readable and reduce complexity
=> Refactor inderes recommendation tracker

build.gradle, src/main/java/com/etsubu/stonksbot/command/EventCommand.java, src/main/java/com/etsubu/stonksbot/configuration/EventConfig.java, src/main/java/com/etsubu/stonksbot/configuration/ServerConfig.java, src/main/java/com/etsubu/stonksbot/services/DatabaseService/DynamodbService.java, src/main/java/com/etsubu/stonksbot/services/DatabaseService/ItemStorage.java
Creates a command that allows simple managing for event registration. Users can register/unregister themselves to a given event in the server. Additionally maximum amount of registered users can be limited, as well as registering can be limited to only given roles on the server
=> Create command for registering to events with role access
